model_name: redlamp_mlp_baseline
input_dim: 38
window_size: 20
latent_dim: 128
mlp_num_linear_layers: 3
classifier_dim: 32
num_classes: 12
dropout: 0.1
lambda_cls: 0.1
use_label_refurbishment: true
refurbishment_alpha: 0.1
refurbishment_beta: 0.01
