task_name: multitask_tsad
use_synthetic_augmentation: true
freeze_fusion_for_epochs: 0
warmup_alpha_value: 0.5
warmup_beta_value: 0.5
anomaly_probability: 0.5
min_segment_fraction: 0.1
max_segment_fraction: 0.2
spike_scale: 3.0
